module.exports = {
  ROLES: {
    WEREWOLF: '🐺',
    VILLAGER: '👤',
    INVESTIGATOR: '🔍',
    BODYGUARD: '🛡️',
    KING: '👑',
    MAYOR: '🏛️',
    DOCTOR: '💉',
    SEDUCTRESS: '💋',
    UM_ZAKI: '🧙',
  },
  PHASES: {
    NIGHT: '🌙',
    DAY: '☀️',
    VOTE: '🗳️',
    LOBBY: '🔄',
  },
  STATUS: {
    ALIVE: '✅',
    DEAD: '💀',
    VOTED: '✔️',
    WAITING: '⏳',
    WIN: '🏆',
    LOSE: '💔',
  },
  BUTTONS: {
    JOIN: '📥',
    LEAVE: '📤',
    START: '▶️',
    VOTE_KILL: '⚔️',
    SAVE: '💊',
    INVESTIGATE: '🔎',
    PROTECT: '🛡️',
    CANCEL: '❌',
    CONFIRM: '✅',
    BACK: '🔙',
  },
  MISC: {
    LOADING: '⏰',
    LOCK: '🔒',
    UNLOCK: '🔓',
    CHANNEL: '📢',
    USER: '👤',
    SETTINGS: '⚙️',
    CROWN: '👑',
    SKULL: '💀',
    HEART: '❤️',
    BROKEN_HEART: '💔',
    DAGGER: '🗡️',
    SHIELD: '🛡️',
    STAR: '⭐',
    FIRE: '🔥',
    SNOWFLAKE: '❄️',
  },
};
